# Generated by Django 4.2 on 2024-02-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('is_download', models.BooleanField(default=False, verbose_name='is download')),
                ('number', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('page', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Libgen scrapper',
            },
        ),
    ]
