# Generated by Django 4.2 on 2024-02-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapperdata',
            name='updated_date',
        ),
    ]
