# Generated by Django 4.2 on 2024-02-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_scrapperdata_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('is_download', models.BooleanField(default=False, verbose_name='is download')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('is_download', models.BooleanField(default=False, verbose_name='is download')),
                ('title', models.CharField(max_length=100, verbose_name='Publisher')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('is_download', models.BooleanField(default=False, verbose_name='is download')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Title',
            },
        ),
        migrations.AlterModelOptions(
            name='scrapperdata',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterField(
            model_name='scrapperdata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Blog.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='scrapperdata',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Blog.publisher', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='scrapperdata',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Blog.title', verbose_name='Title'),
        ),
    ]
